// Estre Logo - Base64 encoded
// TODO: Replace with actual Estre logo Base64 string
export const LOGO_BASE64 = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAoACgDASIAAhEBAxEB/8QAGwAAAgIDAQAAAAAAAAAAAAAAAAcFBgIDBAj/xAAyEAABAwMCBAQEBQUAAAAAAAABAgMEAAURBiESIjFBBxNRYRQycYEjQpGhsRVSYsHR/8QAGAEAAwEBAAAAAAAAAAAAAAAAAgMEBQH/xAAhEQACAgICAgMBAAAAAAAAAAABAgARAyESBEETMVFhwf/aAAwDAQACEQMRAD8A7fhZrOHqHTcyNOlpZkQnkOtLUQAW3AUnb0Ncp7V3ahgF+K0Q4guR3Epb/MgjlB+tZeFcBm3WuSy0Ax55YcWEjrkJR6/SrvIaCMhsYCRxJ+tc1FTLYIEMdoUK6k4rDI5HF/vWafX5R/uvFXQH7e/7oopnxr4wGfb/2gD/xAAbAQADAQEBAQEAAAAAAAAAAAABAgMABAUGB//aAAgBAhAAAAKozE1yJMh1BpP/xAAbAQACAwEBAQAAAAAAAAAAAAAAAQIDBAUGB//aAAgBAxAAAABuGSZEywdQ7kp/2Q==";

// Instructions for replacement:
// 1. Convert your actual Estre logo to Base64
// 2. Use: https://www.base64-image.de/ or similar
// 3. Replace the string above with your full Base64
